#include "ArpFingerprint.h"

using namespace std;

ArpFingerprint::ArpFingerprint() {
	requestAttempts = 0;
	constantRetryTime = false;
	referencedStaleTimeout = 0;
	replyBeforeUpdate = false;
	unicastUpdate = false;

	for (int i = 0; i < 36; i++)
		gratuitousUpdates[i] = false;
}

// Loads in the 1 line string generated by toTinyString()
ArpFingerprint::ArpFingerprint(std::string tinyString) {
	stringstream ss(tinyString);
	ss >> requestAttempts;
	ss >> constantRetryTime;
	ss >> referencedStaleTimeout;
	ss >> replyBeforeUpdate;
	ss >> unicastUpdate;

	for (int i = 0; i < 36; i++) {
		ss >> gratuitousUpdates[i];
	}
}
// Convert to a 1 line string suitable for storage
string ArpFingerprint::toTinyString() {
	stringstream ss;

	ss << requestAttempts << " ";
	ss << constantRetryTime << " ";
	ss << referencedStaleTimeout << " ";
	ss << replyBeforeUpdate << " ";
	ss << unicastUpdate << " ";

	for (int i = 0; i < 36; i++) {
		ss << gratuitousUpdates[i] << " ";
	}

	return ss.str();
}

// User readable string
string ArpFingerprint::toString() {
	stringstream ss;
	ss << "Number of ARP Requests Seen                : " << requestAttempts << endl;
	ss << "Constant retry between attempts            : " << boolalpha << constantRetryTime << endl;
	ss << "Stale timeout value                        : " << referencedStaleTimeout << endl;
	ss << "Replied before ARP request                 : " << boolalpha << replyBeforeUpdate << endl;
	ss << "Got unicast instead of bcast request       : " << boolalpha << unicastUpdate << endl;

	ss << "Gratuitous probe result fingerprint        : ";
	for (int i = 0; i < 36; i++) {
		if (gratuitousUpdates[i]) {
			ss << "1";
		} else {
			ss << "0";
		}
	}

	ss << endl;

	return ss.str();
}


bool ArpFingerprint::operator !=(const ArpFingerprint &rhs) const {
	return !(operator ==(rhs));
}

bool ArpFingerprint::operator ==(const ArpFingerprint &rhs) const {
	if (requestAttempts != rhs.requestAttempts)
		return false;

	if (constantRetryTime != rhs.constantRetryTime)
		return false;

	if (referencedStaleTimeout != rhs.referencedStaleTimeout)
		return false;

	if (replyBeforeUpdate != replyBeforeUpdate)
		return false;

	if (unicastUpdate != rhs.unicastUpdate)
		return false;

	for (int i = 0; i < 36; i++) {
		if (gratuitousUpdates[i] != rhs.gratuitousUpdates[i]) {
			return false;
		}
	}

	return true;
}

